DEFAULT_LAYER_KEYWORDS = [
    "desapropriação",
    "desapropriacao",
    "utilidade pública",
    "utilidade publica",
    "interesse social",
    "dup",
    "dis",
    "desap",
    "área pública",
    "area publica",
    "publica",
    "público",
    "publico",
    "parque",
    "parques",
    "manancial",
    "mananciais",
    "app",
    "preservação",
    "preservacao",
    "ambiental",
    "billings",
    "represa",
    "verde",
    "svma",
    "sehab",
    "habitação",
    "habitacao",
    "zeis",
    "zoneamento",
    "edificação",
    "edificacao",
    "via",
    "vias",
    "logradouro",
    "iluminação",
    "iluminacao",
    "drenagem",
    "galeria",
    "equipamento",
    "serviço público",
    "servico publico",
    "setor censitário",
    "setor censitario",
]

OCCUPATION_LAYER_KEYWORDS = [
    "edificação",
    "edificacao",
    "via",
    "vias",
    "logradouro",
    "iluminação",
    "iluminacao",
    "drenagem",
    "galeria",
    "equipamento",
    "serviço público",
    "servico publico",
    "setor censitário",
    "setor censitario",
]

