DEFAULT_SOURCE_KEYWORDS = [
    "desapropriação",
    "desapropriacao",
    "utilidade pública",
    "utilidade publica",
    "interesse social",
    "área pública",
    "area publica",
    "parque",
    "manancial",
    "billings",
    "preservação",
    "preservacao",
    "ambiental",
    "habitação",
    "habitacao",
    "regularização fundiária",
    "regularizacao fundiaria",
    "zeis",
    "zoneamento",
    "obras",
    "svma",
    "sehab",
    "desap",
]

