DEFAULT_SOURCE_KEYWORDS = [
    "desapropriação",
    "desapropriacao",
    "utilidade pública",
    "utilidade publica",
    "interesse social",
    "área pública",
    "area publica",
    "parque",
    "manancial",
    "billings",
    "preservação",
    "preservacao",
    "ambiental",
    "habitação",
    "habitacao",
    "regularização fundiária",
    "regularizacao fundiaria",
    "zeis",
    "zoneamento",
    "obras",
    "svma",
    "sehab",
    "desap",
    "dup",
    "dis",
    "decreto",
    "processo administrativo",
    "diário oficial",
    "diario oficial",
    "parque linear",
    "app",
    "subprefeitura",
    "vulnerabilidade",
    "auxílio aluguel",
    "auxilio aluguel",
    "empreendimento habitacional",
    "cadastro habitacional",
]


SOURCE_CATEGORY_KEYWORDS = {
    "DESAPROPRIACAO": [
        "desapropriacao",
        "desapropriação",
        "desap",
        "dup",
        "dis",
        "utilidade publica",
        "utilidade pública",
        "expropriatoria",
        "expropriatória",
    ],
    "AREA_PUBLICA": [
        "area publica",
        "área pública",
        "patrimonial",
        "doacao",
        "doação",
        "matricula",
        "matrícula",
        "imovel municipal",
        "imóvel municipal",
    ],
    "HABITACAO": [
        "habitacao",
        "habitação",
        "sehab",
        "auxilio aluguel",
        "auxílio aluguel",
        "regularizacao fundiaria",
        "regularização fundiária",
        "empreendimento habitacional",
        "cadastro habitacional",
    ],
    "PARQUE": [
        "parque",
        "parque linear",
        "unidade de conservacao",
        "unidade de conservação",
        "area verde",
        "área verde",
    ],
    "MANANCIAL_APP": [
        "manancial",
        "mananciais",
        "billings",
        "guarapiranga",
        "app",
        "preservacao permanente",
        "preservação permanente",
        "represa",
    ],
    "ZONEAMENTO": [
        "zeis",
        "zoneamento",
        "pde",
        "lei de parcelamento",
        "uso e ocupacao",
        "uso e ocupação",
    ],
    "DOCUMENTO_OFICIAL": [
        "decreto",
        "lei",
        "processo",
        "diario oficial",
        "diário oficial",
        "planta",
        "croqui",
        "certidao",
        "certidão",
    ],
    "OCUPACAO_INFRAESTRUTURA": [
        "edificacao",
        "edificação",
        "logradouro",
        "iluminacao",
        "iluminação",
        "drenagem",
        "servico",
        "serviço",
        "vulnerabilidade",
        "setor censitario",
        "setor censitário",
    ],
}
